######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 7 17:20:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qt.h
SOURCES += qt.cpp qt_test.cpp
